python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 1 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;


python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;


echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 5 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;


echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;



echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;


echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 15 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 30 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 30 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 30 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 30 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.00001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 30 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;


echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.0005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.001 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.005 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;

echo ==================================================================================;

python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;
python main.py creditFraud credit_fraud_net ../log/mnist_test ../data --objective one-class --lr 0.01 --n_epochs 30 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain False --ae_lr 0.0004 --ae_n_epochs 15 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 0;




